export const userBadges = [
    {
        name:"wildBoar",
        noOfReferrals:"1",
        level:1,
        acquired:false
    },
    {
        name:"panther",
        noOfReferrals:"8",
        level:2,
        acquired:false
    },
    {
        name:"monkey",
        noOfReferrals:"27",
        level:3,
        acquired:false
    },
    {
        name:"wildeBeest",
        noOfReferrals:"64",
        level:4,
        acquired:false
    },
    {
        name:"zebra",
        noOfReferrals:"125",
        level:5,
        acquired:false
    },
    {
        name:"giraffe",
        noOfReferrals:"216",
        level:6,
        acquired:false
    },
    {
        name:"monitorLizard",
        noOfReferrals:"343",
        level:7,
        acquired:false
    },
    {
        name:"honeyBadger",
        noOfReferrals:"512",
        level:8,
        acquired:false
    },
    {
        name:"koala",
        noOfReferrals:"729",
        level:9,
        acquired:false
    },
    {
        name:"snake",
        noOfReferrals:"1000",
        level:10,
        acquired:false
    },
    {
        name:"vulture",
        noOfReferrals:"1331",
        level:11,
        acquired:false
    },
    {
        name:"panda",
        noOfReferrals:"1728",
        level:12,
        acquired:false
    },
    {
        name:"hyena",
        noOfReferrals:"2197",
        level:13,
        acquired:false
    },
    {
        name:"wolf",
        noOfReferrals:"2744",
        level:14,
        acquired:false
    },
    {
        name:"buffalo",
        noOfReferrals:"3375",
        level:15,
        acquired:false
    },
    {
        name:"gorilla",
        noOfReferrals:"4096",
        level:16,
        acquired:false
    },
    {
        name:"eagle",
        noOfReferrals:"4913",
        level:17,
        acquired:false
    },
    {
        name:"bear",
        noOfReferrals:"5832",
        level:18,
        acquired:false
    },
    {
        name:"cheetah",
        noOfReferrals:"6859",
        level:19,
        acquired:false
    },
    {
        name:"crocodile",
        noOfReferrals:"8000",
        level:20,
        acquired:false
    },
    {
        name:"rhino",
        noOfReferrals:"9261",
        level:21,
        acquired:false
    },
    {
        name:"lion",
        noOfReferrals:"10648",
        level:22,
        acquired:false
    },
    {
        name:"tiger",
        noOfReferrals:"12167",
        level:23,
        acquired:false
    },
    {
        name:"dragon",
        noOfReferrals:"13824",
        level:24,
        acquired:false
    },
    {
        name:"trex",
        noOfReferrals:"15625",
        level:25,
        acquired:false
    },
]