export const Strings = {
    COM: "COM",
    DEVI: "DevDevi",
    WELCOME: "Welcome",
    SHARE_LOCATION: "Share your location easily and quickly",
    EXPLORE: "Explore all the Dev's and Devi's around the World. Create Temples Markers on the Map. Create Hindu Festivals on the Map. Showcase our Sanskriti",
    LETS_START: "Let's Start",
    SIGN_IN_WITH: "Sign In With",
    KEEP_DATA: "Keep your data save",
    GOOGLE: "Google",
    FACEBOOK: "Facebook",
    APPLE: "Apple",
    DONATE: "Donate Now",
    SEARCH_LOCATION: "Search Your location",
    NAVIGATE: "Navigate",
    CALL: "Call",
    SHARE: "Share",
    WRITE_REVIEW: "Write a Review",
    WRITE_YOUR_REVIEW: "Write Your Review",
    SHARE_MORE_EXP: "Share more about your experience",
    REVIEW_PLACEHOLDER: "Would you like to write anything about this real estate?",
    UPLOAD_IMAGE_WARNING: "For add/remove Image you have to login first",
    ADD_LOCATION_WARNING: "To add location, please login first",
    ADD_EVENT_WARNING: "For add event you have to login first",
    REVIEW_WARNING: "For add review you have to login first",
    ADD_LOCATION: "Add Location",
    TITLE: "Title",
    EVENT_TITLE: "Event title",
    CATEGORY: "Category",
    DESC: "Description",
    ADDRESS: "Address",
    ADD_IMAGE: "Add Image",
    PHONE: "Phone Number",
    SAVE: "Save",
    TY_ADD_LOCATION: "Thank you for adding location",
    ADMIN_UPDATE: "Admin will review and approve shortly",
    TY_POST: "Thank you For Posting",
    SEE_ALL: "See All",
    DONATION: "Donation",
    HELP: "Help the indonesian kids for better education",
    HOW_MUCH_DONATE: "How Much wanna Donate",
    CONTINUE: "Continue",
    PAY: "Pay",
    PAYMENT: "Payment",
    ADD_CARD: "Add Credit Card",
    ENTER_CREDIT_DETAILS: "Enter your credit details",
    CHOOSE_CARD: "Choose Card",
    TY_DONATION: "Thank you For Donation",
    ABOUT: "About Us",
    TERMS: "Terms and policy",
    FAQ: "FAQ",
    NOTIFICATION: "Notification",
    HISTORY: "My History",
    MY_PROFILE: "My Profile",
    CHANGE_PROFILE: "Change Profile Photo",
    NEW_PROFILE: "New Profile Photo",
    REMOVE_PROFILE: "Remove Profile Photo",
    REMOVE_PROFILE: "Remove Profile Photo",
    NAME: "Name",
    ABOUT_ME: "About me",
    EMAIL: "Email Address",
    INTEREST: "Interest",
    HOME: "Home",
    STATIC1: "User",
    STATIC2: "Properties",
    STATIC3: "Post",
    ERROR: "Someting went wrong! Please try again.",
    CLEAR: "Clear",
    RATING: "Rating",
    APPLY: "Apply",
    RECENT: "Recent",
    ADD_MEDIA: "Add Media",
    ADDTIME: "Add Time",
    OPENINGHOURS: "Opening hours",
    CLOSEHOURS: "Close hours",
    DAY: "Day",
    TO: "To",
    ADDLINK: "Add Link",
    SERVICE: "Service",
    SEE_ALL: "See all",
    NOTHELPFUL: "Not helpful",
    HELPFUL: "helpful",
    REVIEW_COMMENT: "Replay to review",
    REPLAY: "Your replay",
    REPLAY_PLACEHOLDER: "Replaying publicly",
    ADD_EVENT: "Add Event",
    ADD_EVENT_IMAGES: "Add Event Images",
    ADD_EVENT_DATES: "Add Event Dates",
    START_DATE: "Start Date",
    END_DATE: "End Date",
    LOCATION: "Location permission",
    LOCATION_PERMISSION: "Allowing our app to help you discover and explore the closest temples, bringing you closer to meaningful experiences.",
    FB_ERROR: "Someting went wrong from facebook! Please try again.",
}